### GET /
GET http://localhost:5000

### REGISTER a user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "giglamesh@gmail.com",
    "password": "123123123"
}

### LOGIN a user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "giglamesh@gmail.com",
    "password": "123123123"
}

### FETCH all todos GET /TODOS
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3OTQ4MDUxLCJleHAiOjE3NTgwMzQ0NTF9.dGwkyrUqtLC4ryixbYiAoKRWvDR1csz75mPVUwcEyqg

### Creates a new todo POST /TODOS
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3OTQ4MDUxLCJleHAiOjE3NTgwMzQ0NTF9.dGwkyrUqtLC4ryixbYiAoKRWvDR1csz75mPVUwcEyqg
Content-Type: application/json

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID
PUT http://localhost:5000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3OTQ4MDUxLCJleHAiOjE3NTgwMzQ0NTF9.dGwkyrUqtLC4ryixbYiAoKRWvDR1csz75mPVUwcEyqg
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo DELETE /TODOS/:ID
DELETE http://localhost:5000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3OTQ4MDUxLCJleHAiOjE3NTgwMzQ0NTF9.dGwkyrUqtLC4ryixbYiAoKRWvDR1csz75mPVUwcEyqg