### GET /
GET http://localhost:5000

### REGISTER a user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "giglamesh@gmail.com",
    "password": "123123123"
}

### LOGIN a user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "giglamesh@gmail.com",
    "password": "123123123"
}