### GET /
GET http://localhost:5000

### REGISTER a user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "giglamesh@gmail.com",
    "password": "123123123"
}

### LOGIN a user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "giglamesh@gmail.com",
    "password": "123123123"
}

### FETCH all todos GET /TODOS
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3OTQ3NTUxLCJleHAiOjE3NTgwMzM5NTF9.fTjmKVJtCFZUloTJ0Ozl9oSdSWkbQMvaNMV9Od5q9KA

### Creates a new todo POST /TODOS
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3OTQ3NTUxLCJleHAiOjE3NTgwMzM5NTF9.fTjmKVJtCFZUloTJ0Ozl9oSdSWkbQMvaNMV9Od5q9KA
Content-Type: application/json

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID
PUT http://localhost:5000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3OTQ3NTUxLCJleHAiOjE3NTgwMzM5NTF9.fTjmKVJtCFZUloTJ0Ozl9oSdSWkbQMvaNMV9Od5q9KA
Content-Type: application/json

{
    "completed": 1
}